stages:
  - test
  - build
  - test2
  - deploy

install_env:
  stage: test
  script:
  - echo " test 1 ----------------"

run_tests:
  stage: test
  script:
  - echo " test 2 ----------------"

linters:
  stage: test
  script:
  - echo " test inners ----------------"

build:
  stage: build
  script:
  - ./build.sh
  when: manual

test_after_build:
  stage: test2
  script:
  - echo " test after build ----------------"

deploy_job:
  stage: deploy
  script:
  - ./deploy.sh
