stages:
  - test
  - build
  -test2
  -deploy

instal_env:
  stage: test
  script:
  - echo " test 1 ----------------"

run_tests:
  stage: test
  script:
  - echo " test 2 ----------------"

inners:
  stage: test
  script:
  - echo " test inners ----------------"

build:
  stage: build
  script:
  - ./build.sh
  when: manual

test_after_build:
  stage: test
  script:
  - echo " test after build ----------------"

  deploy job:
  stage: deploy
  script:
  - ./deploy.sh
